config/routes.rb
Rails.application.routes.draw do

  get 'pages/index'
  get 'pages/show'
  get 'pages/edit'
  get 'pages/update'
  get 'newspapers/index'
  get 'newspapers/show'
  get 'newspapers/pdf'
  post 'box_photo', to: "newspapers#box_photo"
  post 'change_layout', to: "pages#change_layout"
  delete 'newspapers/:id', to: 'newspapers#destroy'
  post 'back_library', to: "newspapers#back_library"
  resources :messages

  resources :boxes
  resources :tribes
  resources :pictures
  devise_for :users, controllers: { invitations: 'invitations' }
  resources :users, only: [:edit, :show, :update]

  authenticated :user do
    root 'tribes#show'
  end

  root to: 'tribes#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/share/_footer.html.erb
<% unless @no_footer %>
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/mytribunews/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/mytribunews/"><i class="fab fa-facebook"></i></a>
    <a href="https://www.linkedin.com/company/mytribunews/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    copyright <i class="far fa-copyright"></i> by "Tribu News Corp."
  </div>
</div>
<% end %>

app/views/share/_member-action.html.erb
 <div class="action-container">
  <div class="invite">
    <button type="button" class="btn btn-success add-button" data-toggle="modal" data-target="#modalLoginForm" id="add-user-button"> <i class="fas fa-plus" style="margin-right:5px;"></i> Invite family member</button>
  </div>
</div>



<div class="modal fade" id="modalLoginForm" tabindex="1" role="dialog"
aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div>
      <%= form_for( @new_user, url: user_invitation_path,
      html: { id:"form_new_user"}) do |f|%>

      <h4 style="margin-bottom: 6%;">
        Invite your Tribe
      </h4>

      <%= f.hidden_field :tribe_id, value: current_user.tribe.id %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, placeholder: "email", as: :email,
        label:false,  id: "text_font_form_1",
        class: "form-control", required: true %>
      </div>


      <div class="text-center" style="padding: 5%;">
        <%= f.submit "Invite", class: "btn btn-primary" %>
      </div>

      <% end %>
    </div>
  </div>
</div>
</div>

app/views/share/_member-tag.html.erb
 <div class="member-container">
  <figure class="avatar-dashboard">
    <% if user === current_user.tribe.users.first %>
      <div class="member-status member-status-green">
    <% else %>
      <div class="member-status">
    <% end %>
      <!-- here show be a red or green dot for member status -->
    </div>
      <%= cl_image_tag user.photo, alt:'avatar', class: 'avatar avatar-bordered', height: 40, width: 40 %>
  </figure>

  <div class="member-info">
    <%= user.first_name %>
    <%= user.last_name %>
  </div>
</div>

app/views/share/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "TRIBU_Logo_gradient_web_with_alpha.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>

    <%= link_to 'Your tribe', edit_tribe_path(current_user.tribe),class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Edit newspaper", newspapers_show_path, class: "navbar-wagon-item navbar-wagon-link" %>


    <!-- Links when logged in -->
    <!-- TODO LINK TO USER EDIT -->
    <%= link_to "My account", edit_user_registration_path(current_user.id), class: "navbar-wagon-item navbar-wagon-link" %>


    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if current_user.photo? %>
        <%= cl_image_tag current_user.photo, height: 300, width: 400, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
        <%= image_tag "default_user.png", height: 500, width: 500, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <!-- TODO: is this link_to user_path? -->
            <%= link_to edit_user_registration_path(current_user) do %>
            <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>

    <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to  "Sign up" , new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

       <li><%= link_to "my account", root_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
       <% if user_signed_in? %>
       <!-- TODO LINK TO RESERVATIONS -->

       <li>
        <!-- TODO: is this link_to user_path? -->
        <%= link_to "#" do %>
        <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
        <% end %>
       </li>
        <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>

          <% end %>
        </li>
        <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>
</div>

</div>