config/routes.rb
Rails.application.routes.draw do

  get 'pages/index'
  get 'pages/show'
  get 'pages/edit'
  get 'pages/update'
  get 'newspapers/index'
  get 'newspapers/show'
  get 'newspapers/pdf'
  post 'box_photo', to: "newspapers#box_photo"
  post 'change_layout', to: "pages#change_layout"
  delete 'newspapers/:id', to: 'newspapers#destroy'
  post 'back_library', to: "newspapers#back_library"
  resources :messages

  resources :boxes
  resources :tribes
  resources :pictures
  devise_for :users, controllers: { invitations: 'invitations' }
  resources :users, only: [:edit, :show, :update]

  authenticated :user do
    root 'tribes#show'
  end

  root to: 'tribes#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/newspaper.rb
class Newspaper < ApplicationRecord
  belongs_to :tribe
  has_many :pages, dependent: :destroy
  has_many :pictures
end

app/controllers/newspapers_controller.rb
  class NewspapersController < ApplicationController
  layout 'pdf', only: :pdf
  skip_before_action :verify_authenticity_token

  def index
  end

  def show
    @no_footer = true
    @new_picture = Picture.new
    @tribe = current_user.tribe
    @newspaper = @tribe.newspapers.last # normally: last but we work with 1


    if params[:page_number].nil?
      @page = @newspaper.pages.first
    else
      new_page_nr = params[:page_number].to_i
      @page = @newspaper.pages.where(number: new_page_nr).first
    end
    @pic_boxes = get_boxes(@page, :pic)
    @text_boxes = get_boxes(@page, :text)

     respond_to  do |format|
      format.html
      format.pdf do
                   render pdf: "test newspaper",
                   show_as_html: false,         # allow debugging based on url param
                   page_size: 'A4',
                   template: "newspapers/pdf.html.erb",
                   layout: "pdf.html",
                   lowquality: true,
                   zoom: 1.635,
                   :margin => {:top            => 0,                         # default 10 (mm)
                           :bottom             => 0,
                           :left               => 0,
                           :right              => 0}
               end
      end
  end

  def destroy
    tribe = current_user.tribe
    newspaper = tribe.newspapers.last
    @pic = newspaper.pictures.find(params[:id].to_i)
    @pic.destroy
    # redirect_to newspapers_show_path(page_number: params[:page_number])
    redirect_back fallback_location: "newspapers/show?page_number=@page"

  end

  def pdf
   @new_picture = Picture.new
   @tribe = current_user.tribe
   @newspaper = @tribe.newspapers.last

 end

 def box_photo
  pic = Picture.find params[:pic][:picture_id]
  pic.update(box_id: params[:pic][:box_id])
  box = Box.find params[:pic][:box_id]
  box.update(category: params[:pic][:category])
  redirect_to newspapers_show_path(page_number: params[:pic][:page_number])
end

def back_library
  pic = Picture.find params[:photo_box][:picture_id]
  pic.update(box_id: params[:box_id], box_id: nil)
  redirect_to newspapers_show_path(page_number: params[:photo_box][:page_number])

end

private

  def get_boxes(page, category)
    res = []
    page.boxes.order("id ASC").each do |b|
      if category == :pic && !b.picture.nil?
        res << b
      elsif category == :text && b.category == "text"
        res << b
      end
  end
  return res

end
end

app/views/newspapers/index.html.erb
<h1>Newspapers#index</h1>
<p>Find me in app/views/newspapers/index.html.erb</p>

app/views/newspapers/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <style>
      body {
        margin: 0;
        padding: 0;
      }
      .layout {
        margin-top: 50px;
        margin-left: 30px;
      }

      #layout_title, #layout_00 {
        padding:0;
        margin: 0;
        color:white;
      }

      #box_layout_title {
          // height:700px;
          display: flex;
          flex-direction: column;
          justify-content: center;
          text-align:center;
          margin:0;
          padding:0;
          overflow: hidden;
          background: linear-gradient(217deg, hsla(175, 2%, 5%, 0.3), hsla(172, 50%, 26%, .8));
          }

      #box_00_01 {
            padding:0;
            // height:100% !important;
            height: 858px;
            margin: 0;
            width: 100%;
          }
      #box_00_01 img {
        width: 100%;
        margin: 0;
      }
      #box_01_01 {
        width:500px;
        height:700px;
      }

      .photo-box {
        height:100%; //NODIG???
      }

      .text {
        // border: solid 2px rgba(200,200,200,0.3);
        /*box-shadow: 8px 16px 34px -11px rgba(0,0,0,0.12);*/
        border-radius: 5px;
        padding: 10px 2px 10px 0;
        text-align: left;
        margin-top:10px;
        margin-bottom: 10px;
        font-family:"Open Sans";
        font-weight:300;
        color: hsl(172, 100%, 10%);
        display:flex;
        flex-direction:column;
        justify-content:center;
      }

      .photobook_pic {

        background: linear-gradient(217deg, hsla(175, 2%, 10%, 0.3), rgba(0, 185, 160, 0.1));
        margin: 8px;
        // margin-right: 12px;
        /*box-shadow: 8px 16px 34px -11px rgba(0,0,0,0.2);*/
      }

          h1 {
            font-family:"Raleway";
            font-weight:300;
            font-size:45px;
          }
          h2 {
            font-family:"Open Sans";
            font-weight:300;
            font-size:25px;
            margin:30px 0;
          }
          .month {
            margin-top:165px;
            font-weight:700;
            font-size:20px;
          }

        .layout_title_foreground {
          position: absolute;
          text-align: center;
          width: 100vw;
          top :450px;
          left: 150px;
        }
        .layout0-image {
          // overflow: hidden;
          height: 100%;
          object-fit: cover;
          object-position: center;
        }

        #layout_title_logo {
          position:absolute;
          top: 20px;
          right:20px;
          width: 75px;
        }

      #layout_01 {
       display:flex;
       flex-direction: column;
       justify-content: space-between;
       align-items: center;
       padding: 60px 0;
      }

        #layout_02 {
         display:flex;
         flex-direction: column;
         justify-content: space-between;
         align-items: center;
         padding-top: 30px;
       }

       .text {
        position: relative;
        text-align: center;
        display: block;
        height: 100%;
      }

      .text::before, p {
        display: inline-block;
        vertical-align: middle;
      }

      .text::before {
        content: '';
        width: 0;
        height: 100%;
      }
    }

       #box_02_01 {
        width:500px;
        height:550px;
      }

      #box_02_02 {
        width:500px;
        height: 200px;
      }


      #layout_03 {
        display:flex;
        flex-direction: column;
        justify-content: space-between;
        align-items: center;
        padding-top: 30px;
      }

      #box_03_01, #box_03_02 {
        //temp
        width:500px;
        height:380px;
      }

      .empty {
        height:100%;
        background: radial-gradient(hsla(175, 50%, 37%,.2),rgba(255,255,255,.9));
      }


      #layout_04 {
        display:flex;
        flex-direction: column;
        justify-content: space-between;
        align-items: center;
        padding-top: 30px;

      }
      #layout_04 .text {
          height:120px;
        }

      #box_04_01, #box_04_02 {
        //temp
        width:500px;
        height:300px;
      }



      #layout_05 {
        display:flex;
        flex-direction: column;
        justify-content: space-around;
        align-items: center;
      }

      #layout_05 .picture_row {
          display:flex;
          justify-content: space-between;
        }

      #box_05_01, #box_05_02, #box_05_03, #box_05_04 {
        //temp
        width:250px;
        height:320px;
      }

      #box_05_01_pdf, #box_05_02_pdf {
        //temp
        width:250px;
        height:320px;
        display: inline-block;
      }
      #box_05_03_pdf, #box_05_04_pdf {
        width:250px;
        height:320px;
        display: inline-block;
      }



      #layout_06 {
        display:flex;
        flex-direction: column;
        justify-content: space-around;
        align-items: center;
        .picture_row {
          display:flex;
          justify-content: space-between;
        }
      }

      #box_06_01_pdf, #box_06_02_pdf {
        //temp
        width:240px;
        height:300px;
        display: inline-block;
      }

      #box_06_03_pdf, #box_06_04_pdf {
        width:250px;
        height:320px;
        display: inline-block;
      }


      #box_06_05 {
        width:500px;
        height:100px;
      }

      .empty {
        height:100%;
        background: radial-gradient(hsla(175, 50%, 37%,.2),rgba(255,255,255,.9));
      }
.wrapper {
  background-color: #999;
  min-height: 95vh;
  // overflow:hidden;
  display:flex;
  color: white; /* temp */
  h3 {
    margin-top:2px;
    font-size:18px;
    font-weight:300;
    font-family:'Open Sans';
  }
}

.library-pane {
  flex-grow:1;
  background: #777;  /* fallback for old browsers */
  background: linear-gradient(to right, #777, #777 20%, #999);
}

.middle-pane {
  flex: 0 0 700px;
  // display:flex;
  // justify-content:center;
  // align-items:center;
}

.layout-pane {
  // width: 25%;
  min-width:200px;
  // display:hidden;
  background-color: rgba(200,200,200,0.3);
  flex: 0 1 14%;
  /*border: 1px solid green;*/
}

.hidden {
  display:none;
}

.arrow-sign {
  color: hsl(172, 100%, 16%);
}

.library-header, .middle-header, .layout-header {
  padding: 6px 2px 2px 2px;
  background: rgba(20,20,20,.7);
  height: 40px;
  display: flex;
  justify-content: center;
  align-items: center;
}


.nice_button {
  padding: 3px 30px;
  display: flex;
  justify-content: center;
  align-items: center;
  background: rgba(0, 185, 160, 0.05);
  border-radius: 5px;
  /*box-shadow: 6px 4px 10px -1px rgba(0,0,0,0.4);*/
  background-color: rgba(20,20,20,.7);
}

.nice_button#btn_fullscreen{
  padding:5px;
  font-size:24px;
  margin-right:10px;
  position:absolute;
  right: 10px;
}

.library-byheader, .middle-byheader, .layout-byheader {

  background: #00B9A0;
  height: 40px;
  display: flex;
  justify-content: center;
  align-items: center;
  position: relative;
}

.middle-byheader {
  display:flex;
  justify-content:flex-start;
}

#pages_number {
  flex: 1 0 auto;
}

.middle-content {
  display:flex;
  // height:100%;
  // padding:4px;
  min-height:80vh;

}

.page-back, .page-forward {
  flex-grow:0;
  display:flex;
  justify-content: center;
  align-items: center;
  width:50px;
}

.arrow-sign {
  display: block;
  // border: 1px solid green;
  opacity:0.5;
  font-size:25px;

}

.edit-pane {
  margin-top:20px;
  flex-grow:1;
  display:flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;

}

.newspaper_show h3 {
  font-size:22px;
}

.pix-container {
  display:flex;
  flex-wrap: wrap;
  justify-content:flex-start;
  padding:8px;
  align-items: flex-start;
  min-height: 50vh;
  max-height: 95vh;
  overflow-y: auto;

}

.croix{
  position: relative;
  left:18px;
}
.fa-times-circle:hover{
  text-decoration: none;
  color:red;
}
.pic {
  // flex-grow: 1;
  display:flex;
  justify-content:center;
  margin: 8px;
  margin-right: 12px;
 /* box-shadow: 10px 18px 44px -11px rgba(0,0,0,0.72);*/
  border-radius: 5px;

}

.page-edition {
  background-color: white;
  width : 570px;
  height: 860px;
  margin: 0 auto;
  margin-top: 1px;
  color : black;
  text-align: center;
}

#num-change-page {
  color: white;
}

.pic li {
  cursor: grab;
}

.pic li:active {
  cursor: grabbing;
}

.pic li.ghost {
  filter: grayscale(1);
  opacity: 0.5;
}
.fa-times-circle{
  color:red;
}

.layout-content {
    display:flex;
    flex-direction:column;
    justify-content:center;
    align-content:center;
    padding-left:20%;

  }


      div.alwaysbreak { page-break-before: always; }
    </style>
  </head>
  <body>
    <div class="alwaysbreak">
    <%= render "pages/page_layouts_pdf/layout_#{@newspaper.pages[0].layout}", current_page: 0 %>
    </div>
    <div class="alwaysbreak">
    <%= render "pages/page_layouts_pdf/layout_#{@newspaper.pages[1].layout}", current_page: 1 %>
    </div>
    <div class="alwaysbreak">
    <%= render "pages/page_layouts_pdf/layout_#{@newspaper.pages[2].layout}", current_page: 2 %>
    </div>
    <div class="alwaysbreak">
    <%= render "pages/page_layouts_pdf/layout_#{@newspaper.pages[3].layout}", current_page: 3 %>
    </div>
    <div class="alwaysbreak">
    <%= render "pages/page_layouts_pdf/layout_#{@newspaper.pages[4].layout}", current_page: 4 %>
    </div>
    <div class="alwaysbreak">
    <%= render "pages/page_layouts_pdf/layout_#{@newspaper.pages[5].layout}", current_page: 5 %>
    </div>
     <div class="alwaysbreak">
    <%= render "pages/page_layouts_pdf/layout_#{@newspaper.pages[6].layout}", current_page: 6 %>
     </div>
    <div class="alwaysbreak">
    <%= render "pages/page_layouts_pdf/layout_#{@newspaper.pages[7].layout}", current_page: 7 %>
    </div>
    <div class="alwaysbreak">
    <%= render "pages/page_layouts_pdf/layout_#{@newspaper.pages[8].layout}", current_page: 8 %>
    </div>
    <div class="alwaysbreak">
    <%= render "pages/page_layouts_pdf/layout_#{@newspaper.pages[9].layout}", current_page: 9 %>
    </div>
    <div class="alwaysbreak">
    <%= render "pages/page_layouts_pdf/layout_#{@newspaper.pages[10].layout}", current_page: 10 %>
    </div>
    <%= render "pages/page_layouts_pdf/layout_#{@newspaper.pages[11].layout}", current_page: 11 %>
  </body>
</html>

app/views/newspapers/show.html.erb
<%= form_for "layout_picker", url: change_layout_path do |f| %>
<%= f.hidden_field :page_id %>
<%= f.hidden_field :page_layout %>
<%= f.hidden_field :page_number, value: params[:page_number] %>
<% end %>

<%= form_for "photo_box", url: back_library_path do |f| %>
<%= f.hidden_field :picture_id %>
<%= f.hidden_field :page_number, value: params[:page_number] %>
<% end %>

<%= form_for "pic", url: box_photo_path do |f| %>
<%= f.hidden_field :picture_id %>
<%= f.hidden_field :box_id %>
<%= f.hidden_field :page_number, value: params[:page_number] %>
<%= f.hidden_field :category %>
<% end %>

<div class="main-body newspaper-show">
  <div class="wrapper">
    <div class="library-pane">
      <div class="library-byheader">

       <%= simple_form_for @new_picture do |f| %>
       <%= f.input :photo, input_html: { class: 'hidden', id: 'ugly_photo_upload' }, label_html: { class: 'hidden' }  %>
       <%= f.input :photo_cache, as: :hidden %>
       <%= f.hidden_field :page_id, value: @page.id%>
       <%= f.hidden_field :page_layout, value: @page.layout%>
       <% end %>
       <div id="nice_upload_button" class="nice_button">Upload <%= @tribe.name%> pictures</div>
     </div>
     <div class = "library-content">
      <div class="pix-container" id="library">
        <% @newspaper.pictures.each do |pic| %>
        <% if pic.box.nil? %>
        <div class="pic" data-chosen="false" data-id="<%= pic.id %>">
          <div class="croix">
            <%= link_to '',  { action: :destroy, id: pic.id }, method: :delete, data: { confirm: 'Delete this picture ?' } , class: "fas fa-times-circle" %>
          </div>
          <div class="minitoff">
           <%= image_tag pic.photo.url(:thumbnail) %>
           <!-- cl_image_tag(pic.photo, width:350, height:300, crop: :fill)  -->
         </div>
       </div>
       <%end%>
       <% end %>
     </div>
   </div>
 </div>
 <div class="middle-pane">
  <div class="middle-byheader">
    <div class="btn btn-lg" id="pages_number">
      <div class="num" style= "display: none"> <%= @page.number.to_i %> </div>
      <h3 id = "num-change-page"> Page n°<%= @page.number.to_i %></h3>
    </div>
    <div class="buttons-right">
      <div class="nice_button" id="btn_create_pdf"> <%= link_to 'Export PDF', newspapers_show_path(@pdf, :format => :pdf) %>
      </div>
      <!-- <div class="nice_button" id="btn_fullscreen"><i class="fas fa-expand"></i>
      </div> -->
    </div>
  </div>
  <div class="middle-content">
    <div class ="page-back">
      <%= link_to newspapers_show_path(page_number: @page.number.to_i - 1 ) do %>
      <div class="arrow-sign" id = "back-button"><i class="fas fa-arrow-circle-left" ></i></div>
      <% end %>
    </div>
    <div class="edit-pane">
      <div class="page-edition">
        <%= render "pages/show" %>

      </div>

    </div>
    <div class="page-forward">
      <%= link_to newspapers_show_path(page_number: @page.number.to_i + 1) do %>
      <!-- here i could work with a form that does a submit, via js changepage.js -->
      <div class="arrow-sign" id = "forward-button"><i class="fas fa-arrow-circle-right"></i></div>
      <% end %>

    </div>
  </div>
</div>

<div class="layout-pane">
  <div class="layout-byheader">
    <h3>layout</h3>
  </div>
  <div class="layout-content">
    <%= cl_image_tag("https://res.cloudinary.com/df0udw5lo/image/upload/v1553011484/layout_1.png", class:"layout_icon", id:"layout_icon_01", data: { layout:  1})%>
    <%= image_tag("https://res.cloudinary.com/df0udw5lo/image/upload/v1553011484/layout_2.png", class:"layout_icon", id:"layout_icon_02", data: { layout:  2})%>
    <%= image_tag("https://res.cloudinary.com/df0udw5lo/image/upload/v1553011484/layout_3.png", class:"layout_icon", id:"layout_icon_03", data: { layout:  3})%>
    <%= image_tag("https://res.cloudinary.com/df0udw5lo/image/upload/v1553011484/layout_4.png", class:"layout_icon", id:"layout_icon_04", data: { layout:  4})%>
    <%= image_tag("https://res.cloudinary.com/df0udw5lo/image/upload/v1553011484/layout_5.png", class:"layout_icon", id:"layout_icon_05", data: { layout:  5})%>
    <%= image_tag("https://res.cloudinary.com/df0udw5lo/image/upload/v1553011484/layout_6.png", class:"layout_icon", id:"layout_icon_06", data: { layout:  6})%>
  </div>

</div>
</div>
<script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript"></script>
</div>

<script>
  const elem = document.querySelector('.fa-times-circle');
  console.log(elem);
  const myScript = () => {
    console.log('hello'); };
  </script>

app/views/newspapers/show.js.erb
// updatePageLayout(document.getElementById("picture_page_layout").value);

app/views/newspapers/temp_show.html.erb
<div class="main-body newspaper-show">
  <div class="wrapper">
    <div class="library-pane">
      <div class ="library-header">
        <h3><%= @tribe.name%>'pictures</h3>
      </div>
      <div class="library-byheader">
       <%= simple_form_for @new_picture do |f| %>
       <%= f.input :photo, input_html: { class: 'hidden', id: 'ugly_photo_upload' }, label_html: { class: 'hidden' }  %>
       <%= f.input :photo_cache, as: :hidden %>
       <% end %>
       <div id="nice_upload_button" class="nice_button">add new pictures</div>
     </div>
     <div class = "library-content">
      <div class="pix-container" id="library">
          <% @newspaper.pictures.each do |pic| %>
             <% if pic.box.nil? %>
             <div class="pic" data-chosen="false" data-id="<%= pic.id %>">
                <%= link_to '',  { action: :destroy, id: pic.id }, method: :delete, data: { confirm: 'Are you sure?' } , class: "fas fa-times-circle" %>
               <%= cl_image_tag(pic.photo,
                 width:150, height:150, crop: :fill) %>
              </div>
             <%end%>
           <% end %>
      </div>
    </div>
  </div>
  <div class="middle-pane">
    <div class ="middle-header">
      <h3>edit your pages</h3>
    </div>
    <div class="middle-byheader">
      <div class="btn btn-lg" id="pages_number">
        <span class="num" style= "display: none"> <%= i = 1  %> </span>
        <h3 id = "num-change-page"> Page n°<%= @newspaper.pages[i - 1][:number]%></h3>
      </div>
      <div class="nice_button" id="btn_fullscreen"><i class="fas fa-expand"></i>
      </div>
    </div>
    <div class="middle-content">
      <div class ="page-back">
        <span class="arrow-sign" id = "back-button"><i class="fas fa-arrow-circle-left" ></i></span>
      </div>
      <div class="edit-pane">
        <div class="page-edition">
          <!--  -->
             <!-- default layout... maybe to remove if all works well -->
          <% @page.layout = "2" %>
           <!-- @page.layout = "2" if @page.layout.nil?  -->


          <%= render "pages/page_layouts/layout_0"+@page.layout %>
        </div>

      </div>
      <div class="page-forward">
        <!-- here i could work with a form that does a submit, via js changepage.js -->
        <span class="arrow-sign" id = "forward-button"><i class="fas fa-arrow-circle-right"></i></span>
      </div>
    </div>
  </div>

  <div class="layout-pane">
    <div class ="layout-header">
      <h3>page layout</h3>
    </div>
    <div class="layout-byheader">
    </div>

    <div class="layout-content">
      <%= image_tag("layouts/layout_00", class:"layout_icon", id:"layout_icon_01")%>
      <%= image_tag("layouts/layout_01", class:"layout_icon", id:"layout_icon_02")%>
      <%= image_tag("layouts/layout_02", class:"layout_icon layout_active", id:"layout_icon_03")%>
      <%= image_tag("layouts/layout_03", class:"layout_icon", id:"layout_icon_04")%>
      <%= image_tag("layouts/layout_04", class:"layout_icon", id:"layout_icon_05")%>
      <%= image_tag("layouts/layout_05", class:"layout_icon", id:"layout_icon_06")%>
    </div>
  </div>
</div>
<script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript"></script>
</div>

<script>
  const elem = document.querySelector('.fa-times-circle');
  console.log(elem);
  const myScript = () => {
    console.log('hello'); };
</script>